#!/bin/bash

yarn build:packages

packages=(
  "constants"
  "lit-node-client"
  "lit-auth-client"
  "pkp-base"
  "pkp-cosmos"
  "pkp-ethers"
  "pkp-client"
  "pkp-walletconnect"
  "types"
)

# then in your project, do `npm link @lit-protocol/lit-node-client`

pids=()
for package in "${packages[@]}"; do
  cd packages/$package && npm link && cd ../..
  pids+=($!)
done