#!/bin/bash

yarn build:packages

packages=(
  "lit-node-client"
  "types"
  "pkp-cosmos"
  "pkp-ethers"
)

# then in your project, do `npm link @lit-protocol/lit-node-client`

pids=()
for package in "${packages[@]}"; do
  cd packages/$package && npm link && cd ../..
  pids+=($!)
done