config:
  target: "dummy"
  phases:
    # Over 60s, ramp up to creating 50 vusers per second
    - duration: 60
      arrivalRate: 5
      rampTo: 150
      name: "Ramp Up"
    # Over 300s, create 50 vusers per second
    - duration: 300
      arrivalRate: 150
      name: "Sustained Encrypt & Decrypt"
    # Over 60s, ramp down to creating 5 vusers per second
    - duration: 60
      arrivalRate: 20
      name: "Ramp Down"
  processor: "../src/processors/multi-endpoints.ts"

scenarios:
  - name: "Encrypt & Decrypt Stress Test"
    weight: 100
    flow:
      - function: "runEncryptDecryptTest"
      - think: 0.1 