config:
  target: "dummy" # Not used but required by Artillery
  phases:
    - duration: 60
      arrivalRate: 3
      maxVusers: 15
      name: "Ramp Up"
    - duration: 240
      arrivalRate: 8
      maxVusers: 30
      name: "Sustained Encrypt/Decrypt"
    - duration: 60
      arrivalRate: 3
      maxVusers: 15
      name: "Ramp Down"
  processor: "../processors/multi-endpoint.ts"
  http:
    defaults:
      think:
        jitter: 75
  variables:
    parallelism: 6
    testSuite: "encrypt-decrypt-focused"

scenarios:
  - name: "PKP Encrypt/Decrypt Flow"
    weight: 50
    flow:
      - function: "runPkpEncryptDecryptTest"
  - name: "Complete Encrypt/Decrypt Flow"
    weight: 50
    flow:
      - function: "runEncryptDecryptFlowTest" 