config:
  target: 'dummy'
  phases:
    # Over 60s, ramp up to creating 50 vusers per second
    - duration: 60
      arrivalRate: 5
      rampTo: 75
      name: 'Ramp Up'
    # Over 300s, create 50 vusers per second
    - duration: 300
      arrivalRate: 75
      name: 'Sustained Encrypt & Decrypt'
    # Over 60s, ramp down to creating 5 vusers per second
    - duration: 60
      arrivalRate: 20
      name: 'Ramp Down'
  processor: '../src/processors/multi-endpoints.ts'

scenarios:
  - name: 'PKP Sign Stress Test'
    weight: 50
    flow:
      - function: 'runPkpSignTest'
      - think: 0.1
  - name: 'Encrypt & Decrypt Stress Test'
    weight: 25
    flow:
      - function: 'runEncryptDecryptTest'
      - think: 0.1
  - name: 'Execute JS Stress Test'
    weight: 25
    flow:
      - function: 'runExecuteJSTest'
      - think: 0.1
