config:
  target: "dummy"
  phases:
    - duration: 60
      arrivalRate: 5
      maxVusers: 20
      name: "Ramp Up"
    - duration: 300
      arrivalRate: 15
      maxVusers: 50
      name: "Sustained PKP Signing"
    - duration: 60
      arrivalRate: 5
      maxVusers: 20
      name: "Ramp Down"
  processor: "../src/processors/pkpSign.ts"
  environments:
    production:
      target: "dummy"

scenarios:
  - name: "PKP Sign Load Test"
    weight: 100
    flow:
      - function: "runPkpSignTest"
      - think: 2 