config:
  target: "dummy" # Not used but required by Artillery
  phases:
    - duration: 120
      arrivalRate: 10
      maxVusers: 50
      name: "Initial Ramp Up"
    - duration: 240
      arrivalRate: 25
      maxVusers: 100
      name: "High Load"
    - duration: 180
      arrivalRate: 50
      maxVusers: 200
      name: "Peak Stress"
    - duration: 120
      arrivalRate: 10
      maxVusers: 50
      name: "Cool Down"
  processor: "../processors/multi-endpoint.ts"
  http:
    defaults:
      think:
        jitter: 50
  variables:
    parallelism: 10
    testSuite: "stress"

scenarios:
  - name: "PKP Sign Stress Test"
    weight: 50
    flow:
      - function: "runPkpSignTest"
  - name: "Encrypt/Decrypt Stress Test"
    weight: 30
    flow:
      - function: "runEncryptDecryptTest"
  - name: "Execute JS Stress Test"
    weight: 20
    flow:
      - function: "runExecuteJsTest" 