// THIS FILE IS AUTOMATICALLY GENERATED FROM tools/scripts/gen-nodejs.mjs 

import { hasItems } from './helper';

import * as accessControlConditions from '@litprotocol-dev/access-control-conditions';
import * as authBrowser from '@litprotocol-dev/auth-browser';
import * as blsSdk from '@litprotocol-dev/bls-sdk';
import * as constants from '@litprotocol-dev/constants';
import * as crypto from '@litprotocol-dev/crypto';
import * as ecdsaSdk from '@litprotocol-dev/ecdsa-sdk';
import * as encryption from '@litprotocol-dev/encryption';
import * as litNodeClient from '@litprotocol-dev/lit-node-client';
import * as misc from '@litprotocol-dev/misc';
import * as miscBrowser from '@litprotocol-dev/misc-browser';
import * as uint8arrays from '@litprotocol-dev/uint8arrays';

console.log("accessControlConditions:", hasItems(accessControlConditions));
console.log("authBrowser:", hasItems(authBrowser));
console.log("blsSdk:", hasItems(blsSdk));
console.log("constants:", hasItems(constants));
console.log("crypto:", hasItems(crypto));
console.log("ecdsaSdk:", hasItems(ecdsaSdk));
console.log("encryption:", hasItems(encryption));
console.log("litNodeClient:", hasItems(litNodeClient));
console.log("misc:", hasItems(misc));
console.log("miscBrowser:", hasItems(miscBrowser));
console.log("uint8arrays:", hasItems(uint8arrays));