// This file is auto-generated by tools/scripts/gen-internal-dev.mjs
export const INTERNAL_DEV = [];

export const INTERNAL_MIN_NODE_COUNT = 3;

export const INTERNAL_DEFAULT_CONFIG = {
  alertWhenUnauthorized: false,
  minNodeCount: 3,
  debug: true,
  bootstrapUrls: [],
  litNetwork: 'internalDev',
  connectTimeout: 20000,
};
