// This file is auto-generated by tools/scripts/gen-internal-dev.mjs
export const INTERNAL_DEV = [
  'https://158.69.34.226:443',
  'https://158.69.34.228:443',
  'https://158.69.34.227:443',
  'https://167.114.17.203:443',
  'https://167.114.17.205:443',
];

export const INTERNAL_MIN_NODE_COUNT = 3;

export const INTERNAL_DEFAULT_CONFIG = {
  alertWhenUnauthorized: false,
  minNodeCount: 3,
  debug: true,
  bootstrapUrls: [
    'https://158.69.34.226:443',
    'https://158.69.34.228:443',
    'https://158.69.34.227:443',
    'https://167.114.17.203:443',
    'https://167.114.17.205:443',
  ],
  litNetwork: 'internalDev',
  connectTimeout: 20000,
};
