/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface DomainWalletOracleInterface extends utils.Interface {
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "checkRegistration(bytes)": FunctionFragment;
    "contractResolver()": FunctionFragment;
    "env()": FunctionFragment;
    "getDomainIdByTokenId(uint256)": FunctionFragment;
    "getDomainTokenIdByUri(bytes)": FunctionFragment;
    "getDomainUri(uint256)": FunctionFragment;
    "getExpiration(uint256)": FunctionFragment;
    "getPkpTokenId(uint64)": FunctionFragment;
    "getRecord(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasExpired(uint256)": FunctionFragment;
    "hasOwner(uint256)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isOwner(uint256)": FunctionFragment;
    "isRouted(uint256)": FunctionFragment;
    "registerDomain(bytes,bytes,uint256,uint256)": FunctionFragment;
    "registerPKP(uint64,uint256)": FunctionFragment;
    "removeDomain(uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeDomain(uint256)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "updateDomainRecord(uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "checkRegistration"
      | "contractResolver"
      | "env"
      | "getDomainIdByTokenId"
      | "getDomainTokenIdByUri"
      | "getDomainUri"
      | "getExpiration"
      | "getPkpTokenId"
      | "getRecord"
      | "getRoleAdmin"
      | "grantRole"
      | "hasExpired"
      | "hasOwner"
      | "hasRole"
      | "isOwner"
      | "isRouted"
      | "registerDomain"
      | "registerPKP"
      | "removeDomain"
      | "renounceRole"
      | "revokeDomain"
      | "revokeRole"
      | "setAdmin"
      | "supportsInterface"
      | "updateDomainRecord"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkRegistration",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractResolver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "env", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDomainIdByTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainTokenIdByUri",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainUri",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpiration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPkpTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRouted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDomain",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPKP",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDomain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDomain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "setAdmin", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDomainRecord",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "env", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDomainIdByTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainTokenIdByUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpiration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPkpTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRouted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPKP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDomainRecord",
    data: BytesLike
  ): Result;

  events: {
    "Expired(bytes,uint256,uint256)": EventFragment;
    "Registered(uint64,bytes,uint256,uint256)": EventFragment;
    "Removed(uint256,bytes)": EventFragment;
    "Revoked(uint256,bytes)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Expired"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Registered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Removed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Revoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface ExpiredEventObject {
  subDomain: string;
  tokenId: BigNumber;
  ttl: BigNumber;
}
export type ExpiredEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ExpiredEventObject
>;

export type ExpiredEventFilter = TypedEventFilter<ExpiredEvent>;

export interface RegisteredEventObject {
  id: BigNumber;
  subDomain: string;
  ttl: BigNumber;
  tokenId: BigNumber;
}
export type RegisteredEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  RegisteredEventObject
>;

export type RegisteredEventFilter = TypedEventFilter<RegisteredEvent>;

export interface RemovedEventObject {
  tokenId: BigNumber;
  subDomain: string;
}
export type RemovedEvent = TypedEvent<[BigNumber, string], RemovedEventObject>;

export type RemovedEventFilter = TypedEventFilter<RemovedEvent>;

export interface RevokedEventObject {
  tokenId: BigNumber;
  subDomain: string;
}
export type RevokedEvent = TypedEvent<[BigNumber, string], RevokedEventObject>;

export type RevokedEventFilter = TypedEventFilter<RevokedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface DomainWalletOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DomainWalletOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    checkRegistration(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    contractResolver(overrides?: CallOverrides): Promise<[string]>;

    env(overrides?: CallOverrides): Promise<[number]>;

    getDomainIdByTokenId(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getDomainTokenIdByUri(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getDomainUri(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getExpiration(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPkpTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRecord(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    hasExpired(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    hasOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isRouted(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registerDomain(
      userId: BytesLike,
      uri: BytesLike,
      pkpTokenId: BigNumberish,
      ttl: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    registerPKP(
      id: BigNumberish,
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    removeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setAdmin(
      acct: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    updateDomainRecord(
      pkpTokenId: BigNumberish,
      record: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  checkRegistration(uri: BytesLike, overrides?: CallOverrides): Promise<void>;

  contractResolver(overrides?: CallOverrides): Promise<string>;

  env(overrides?: CallOverrides): Promise<number>;

  getDomainIdByTokenId(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDomainTokenIdByUri(
    uri: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getDomainUri(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getExpiration(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPkpTokenId(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRecord(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  hasExpired(
    pkpTokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  hasOwner(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOwner(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRouted(
    pkpTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  registerDomain(
    userId: BytesLike,
    uri: BytesLike,
    pkpTokenId: BigNumberish,
    ttl: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  registerPKP(
    id: BigNumberish,
    pkpTokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  removeDomain(
    pkpTokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeDomain(
    pkpTokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setAdmin(
    acct: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  updateDomainRecord(
    pkpTokenId: BigNumberish,
    record: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    checkRegistration(uri: BytesLike, overrides?: CallOverrides): Promise<void>;

    contractResolver(overrides?: CallOverrides): Promise<string>;

    env(overrides?: CallOverrides): Promise<number>;

    getDomainIdByTokenId(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainTokenIdByUri(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainUri(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getExpiration(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPkpTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecord(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasExpired(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRouted(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registerDomain(
      userId: BytesLike,
      uri: BytesLike,
      pkpTokenId: BigNumberish,
      ttl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    registerPKP(
      id: BigNumberish,
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeDomain(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeDomain(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAdmin(acct: string, overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateDomainRecord(
      pkpTokenId: BigNumberish,
      record: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Expired(bytes,uint256,uint256)"(
      subDomain?: null,
      tokenId?: null,
      ttl?: null
    ): ExpiredEventFilter;
    Expired(subDomain?: null, tokenId?: null, ttl?: null): ExpiredEventFilter;

    "Registered(uint64,bytes,uint256,uint256)"(
      id?: null,
      subDomain?: null,
      ttl?: null,
      tokenId?: null
    ): RegisteredEventFilter;
    Registered(
      id?: null,
      subDomain?: null,
      ttl?: null,
      tokenId?: null
    ): RegisteredEventFilter;

    "Removed(uint256,bytes)"(
      tokenId?: null,
      subDomain?: null
    ): RemovedEventFilter;
    Removed(tokenId?: null, subDomain?: null): RemovedEventFilter;

    "Revoked(uint256,bytes)"(
      tokenId?: null,
      subDomain?: null
    ): RevokedEventFilter;
    Revoked(tokenId?: null, subDomain?: null): RevokedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    checkRegistration(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    contractResolver(overrides?: CallOverrides): Promise<BigNumber>;

    env(overrides?: CallOverrides): Promise<BigNumber>;

    getDomainIdByTokenId(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainTokenIdByUri(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainUri(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExpiration(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPkpTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecord(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    hasExpired(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    hasOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRouted(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerDomain(
      userId: BytesLike,
      uri: BytesLike,
      pkpTokenId: BigNumberish,
      ttl: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    registerPKP(
      id: BigNumberish,
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    removeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setAdmin(
      acct: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateDomainRecord(
      pkpTokenId: BigNumberish,
      record: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkRegistration(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    contractResolver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    env(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDomainIdByTokenId(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDomainTokenIdByUri(
      uri: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDomainUri(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExpiration(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPkpTokenId(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecord(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    hasExpired(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    hasOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRouted(
      pkpTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerDomain(
      userId: BytesLike,
      uri: BytesLike,
      pkpTokenId: BigNumberish,
      ttl: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    registerPKP(
      id: BigNumberish,
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    removeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeDomain(
      pkpTokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      acct: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateDomainRecord(
      pkpTokenId: BigNumberish,
      record: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
