import {
  CASE_000_EXPORTS,
} from './cases/CASE_000_EXPORTS'

import { 
  CASE_001_ENCRYPT_AND_DECRYPT_STRING
} from './cases/CASE_001_ENCRYPT_AND_DECRYPT_STRING';

import { 
  CASE_002_ENCRYPT_AND_DECRYPT_ZIP_WITH_AN_UPDATE,
} from './cases/CASE_002_ENCRYPT_AND_DECRYPT_ZIP_WITH_AN_UPDATE';


export const testCases = [
  ...CASE_000_EXPORTS,
  ...CASE_001_ENCRYPT_AND_DECRYPT_STRING,
  ...CASE_002_ENCRYPT_AND_DECRYPT_ZIP_WITH_AN_UPDATE,
]