import { z } from 'zod';

export const ChainEnumAtom = z.enum([
  'cosmos',
  'kyve',
  'evmosCosmos',
  'evmosCosmosTestnet',
  'cheqdMainnet',
  'cheqdTestnet',
  'juno',
]);

export const EvmChainEnum = z.enum([
  'ethereum',
  'polygon',
  'fantom',
  'xdai',
  'bsc',
  'arbitrum',
  'arbitrumSepolia',
  'avalanche',
  'fuji',
  'harmony',
  'mumbai',
  'goerli',
  'cronos',
  'optimism',
  'celo',
  'aurora',
  'eluvio',
  'alfajores',
  'xdc',
  'evmos',
  'evmosTestnet',
  'bscTestnet',
  'baseGoerli',
  'baseSepolia',
  'moonbeam',
  'moonriver',
  'moonbaseAlpha',
  'filecoin',
  'hyperspace',
  'sepolia',
  'scrollAlphaTestnet',
  'scroll',
  'zksync',
  'base',
  'lukso',
  'luksoTestnet',
  'zora',
  'zoraGoerli',
  'zksyncTestnet',
  'lineaGoerli',
  'lineaSepolia',
  'chronicleTestnet',
  'yellowstone',
  'lit',
  'chiado',
  'zkEvm',
  'mantleTestnet',
  'mantle',
  'klaytn',
  'publicGoodsNetwork',
  'optimismGoerli',
  'waevEclipseTestnet',
  'waevEclipseDevnet',
  'verifyTestnet',
  'fuse',
  'campNetwork',
  'vanar',
  'lisk',
  'chilizMainnet',
  'chilizTestnet',
  'skaleTestnet',
  'skale',
  'skaleCalypso',
  'fhenixHelium',
  'hederaTestnet',
  'bitTorrentTestnet',
  'storyIlaid',
  'campTestnet',
  'hushedNorthstar',
]);

export const ChainEnumSol = z.enum(['solana', 'solanaDevnet', 'solanaTestnet']);

export const ReturnValueTestSchema = z
  .object({
    key: z.string(),
    comparator: z.enum(['contains', '=', '>', '>=', '<', '<=']),
    value: z.string(),
  })
  .strict();
