name: E2E - Naga (matrix)

on:
  push:
    branches: [naga, canary-naga]
  pull_request:

env:
  LOCAL_MASTER_ACCOUNT: ${{ secrets.LOCAL_MASTER_ACCOUNT }}
  LOG_LEVEL: debug2

jobs:
  e2e:
    name: E2E (${{ matrix.network }})
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: naga-dev
            network: naga-dev
          - environment: naga-staging
            network: naga-staging
          - environment: naga-test
            network: naga-test

    env:
      # Pulled from the environment-scoped secret of the active matrix environment
      LIVE_MASTER_ACCOUNT: ${{ secrets.LIVE_MASTER_ACCOUNT }}

    steps:
      # ==================== Base Env Setup (shared) ====================
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-std

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # ==================== Run Build (shared) ====================
      - name: Build
        run: pnpm build

      # ==================== Run Tests (varies by matrix) ====================
      - name: Run health check (${{ matrix.network }})
        run: NETWORK=${{ matrix.network }} pnpm run test:e2e:ci all
        timeout-minutes: 10
