name: E2E Tests

on:
  push:
    branches:
      - naga
      - canary-naga
  pull_request:
env:
  LIT_STATUS_WRITE_KEY: ${{ secrets.LIT_STATUS_WRITE_KEY }}
  LIT_STATUS_BACKEND_URL: ${{ vars.LIT_STATUS_BACKEND_URL }}
  LIVE_MASTER_ACCOUNT: ${{ secrets.LIVE_MASTER_ACCOUNT }}
  LOCAL_MASTER_ACCOUNT: ${{ secrets.LOCAL_MASTER_ACCOUNT }}
  LOG_LEVEL: info

jobs:
  naga-e2e-tests:
    runs-on: ubuntu-latest
    environment: Health Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-std

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install Bun dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Run health check for naga-dev
        run: NETWORK=naga-dev bun run test:e2e all
        timeout-minutes: 10

      # - name: Run health check for naga-test
      #   run: NETWORK=naga-test bun run test:e2e all
      #   timeout-minutes: 10

      - name: Run health check for naga-staging
        run: NETWORK=naga-staging bun run test:e2e all
        timeout-minutes: 10