name: E2E Tests

on:
  push:
    branches:
      - naga
      - canary-naga
  pull_request:
env:
  LIT_STATUS_WRITE_KEY: ${{ secrets.LIT_STATUS_WRITE_KEY }}
  LIT_STATUS_BACKEND_URL: ${{ vars.LIT_STATUS_BACKEND_URL }}
  LIVE_MASTER_ACCOUNT: ${{ secrets.LIVE_MASTER_ACCOUNT }}
  LOCAL_MASTER_ACCOUNT: ${{ secrets.LOCAL_MASTER_ACCOUNT }}
  LOG_LEVEL: info

jobs:
  naga-e2e-tests:
    runs-on: ubuntu-latest
    environment: Health Check
    steps:
      # ==================== Base Env Setup ====================
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-std

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # ==================== Run Build ====================
      - name: Build
        run: pnpm build

      # ==================== Run Tests ====================
      - name: Run health check for naga-dev
        run: NETWORK=naga-dev pnpm run test:e2e:ci all
        timeout-minutes: 10

      - name: Run health check for naga-test
        run: NETWORK=naga-test pnpm run test:e2e:ci all
        timeout-minutes: 10

      - name: Run health check for naga-staging
        run: NETWORK=naga-staging pnpm run test:e2e:ci all
        timeout-minutes: 10
