name: E2E Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      naga_branch:
        description: 'Branch for Naga tests'
        required: true
        default: 'master'
env:
  LIT_STATUS_WRITE_KEY: ${{ secrets.LIT_STATUS_WRITE_KEY }}
  LIT_STATUS_BACKEND_URL: ${{ vars.LIT_STATUS_BACKEND_URL }}
  LIVE_MASTER_ACCOUNT: ${{ vars.LIVE_MASTER_ACCOUNT }}
jobs:
  naga-e2e-tests:
    runs-on: ubuntu-latest
    environment: Health Check
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-std

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install Bun dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Run health check for naga-dev
        run: NETWORK=naga-dev bun run test:e2e pkpSign

      - name: Run health check for naga-staging
        run: NETWORK=naga-staging bun run test:e2e pkpSign

      - name: Run health check for naga-local
        run: NETWORK=naga-local bun run test:e2e pkpSign